using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Globalization;

namespace BillingSoft
{
    public partial class AutoGeneratedBill : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            getDetailofmonthly();
            //getDetailofsixmonth();
        }
        private void getDetailofmonthly()
        {
            string query = "select * from Ledger_Main_log where RepeatInfo ='1'";
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["mycs"].ConnectionString;
            SqlConnection connection = new SqlConnection(ConnectionString);
            SqlDataAdapter adapter = new SqlDataAdapter(query, connection);
            adapter = new SqlDataAdapter(query, connection);
            DataTable dtCustomerdetails = new DataTable();

            connection.Open();
            adapter.Fill(dtCustomerdetails);
        

            var CustomerId = (from r in dtCustomerdetails.AsEnumerable()
                              select r["CustomerId"]).Distinct().ToList();


            DataView dv = new DataView(dtCustomerdetails);
            foreach (var item in CustomerId)
            {

                dv.RowFilter = "CustomerId = " + item + "";
                DataTable dtofitems = new DataTable();
                dtofitems = dv.ToTable();


                foreach (DataRow row in dtofitems.Rows)
                {
                    string dateInString = row["DateBillCreated"].ToString();
                    DateTime startDate = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);

                    string today = DateTime.Now.ToString("dd-MM-yyyy");

                    string formattedStartDate = startDate.ToString("dd-MM-yyyy HH:mm", CultureInfo.InvariantCulture);
                    DateTime d = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                    DateTime expiryDate = d.AddDays(30);

                    string formattedexpiryDate = expiryDate.ToString("dd-MM-yyyy");
                    if (today == formattedexpiryDate)
                    {
                        string insertQuery = "insert into " +
                     "Ledger_Main_log (InvoiceNo,Company_Name,CustomerId,Credit,Debit,Balance,Payment_Mode,RepeatInfo,Cheque_No,DateBillCreated) " +
                     "values(@InvoiceNo,@Company_Name,@CustomerId,@Credit,@Debit,@Balance,@Payment_Mode,@RepeatInfo,@Cheque_No,@DateBillCreated)";


                        SqlCommand cmd2 = new SqlCommand(insertQuery, connection);

                        string cmpnynm = row["Company_Name"].ToString();
                        string res = cmpnynm.Substring(0, 3).ToUpper();
                        string invoiceno = res + DateTime.Now.ToString("yyyy") + GenerateRandomNo();


                        string customerid = row["CustomerId"].ToString();
                        string Credit = row["Credit"].ToString();
                        string Debit = row["Debit"].ToString();
                        string Balance = (int.Parse(row["Balance"].ToString()) + GetDuebyid(customerid)).ToString();
                        string Payment_Mode = row["Payment_Mode"].ToString();
                        string RepeatInfo = "0";
                        string Cheque_No = "0";
                        string DateBillCreated = today;

                        cmd2.Parameters.AddWithValue("@InvoiceNo", invoiceno);
                        cmd2.Parameters.AddWithValue("@Company_Name", cmpnynm);
                        cmd2.Parameters.AddWithValue("@CustomerId", customerid);
                        cmd2.Parameters.AddWithValue("@Credit", Credit);
                        cmd2.Parameters.AddWithValue("@Debit", Debit);
                        cmd2.Parameters.AddWithValue("@Balance", Balance);
                        cmd2.Parameters.AddWithValue("@RepeatInfo", RepeatInfo);
                        cmd2.Parameters.AddWithValue("@Payment_Mode", Payment_Mode);
                        cmd2.Parameters.AddWithValue("@Cheque_No", Cheque_No);
                        cmd2.Parameters.AddWithValue("@DateBillCreated", DateBillCreated);


                        cmd2.ExecuteNonQuery();

                        Response.Write("<br>data Inserted;invoice is:" + invoiceno);
                    }
                    else
                    {



                        Response.Write("bill generate");
                    }
                }
               

            }
            connection.Close();
        }





    
    /*private void getDetailofsixmonth()
    {
            string query = "select * from Ledger_Main_log where RepeatInfo ='6'";
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["mycs"].ConnectionString;
            SqlConnection connection = new SqlConnection(ConnectionString);
            SqlDataAdapter adapter = new SqlDataAdapter(query, connection);
            adapter = new SqlDataAdapter(query, connection);
            DataTable dtCustomerdetails = new DataTable();

            connection.Open();
            adapter.Fill(dtCustomerdetails);


            var CustomerId = (from r in dtCustomerdetails.AsEnumerable()
                              select r["CustomerId"]).Distinct().ToList();


            DataView dv = new DataView(dtCustomerdetails);
            foreach (var item in CustomerId)
            {

                dv.RowFilter = "CustomerId = " + item + "";
                DataTable dtofitems = new DataTable();
                dtofitems = dv.ToTable();


                foreach (DataRow row in dtofitems.Rows)
                {
                    string dateInString = row["DateBillCreated"].ToString();
                    DateTime startDate = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);

                    string today = DateTime.Now.ToString("dd-MM-yyyy");

                    string formattedStartDate = startDate.ToString("dd-MM-yyyy HH:mm", CultureInfo.InvariantCulture);
                    DateTime d = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                    DateTime expiryDate = d.AddDays(180);

                    string formattedexpiryDate = expiryDate.ToString("dd-MM-yyyy");
                    if (today == formattedexpiryDate)
                    {
                        Response.Write("bill generate");
                    }
                    else
                    {
                        string insertQuery = "insert into " +
                     "Ledger_Main_log (InvoiceNo,Company_Name,CustomerId,Credit,Debit,Balance,Payment_Mode,RepeatInfo,Cheque_No,DateBillCreated) " +
                     "values(@InvoiceNo,@Company_Name,@CustomerId,@Credit,@Debit,@Balance,@Payment_Mode,@RepeatInfo,@Cheque_No,@DateBillCreated)";


                        SqlCommand cmd2 = new SqlCommand(insertQuery, connection);

                        string cmpnynm = row["Company_Name"].ToString();
                        string res = cmpnynm.Substring(0, 3).ToUpper();
                        string invoiceno = res + DateTime.Now.ToString("yyyy") + GenerateRandomNo();


                        string customerid = row["CustomerId"].ToString();
                        string Credit = row["Credit"].ToString();
                        string Debit = row["Debit"].ToString();
                        string Balance = (int.Parse(row["Balance"].ToString()) + GetDuebyid(customerid)).ToString();
                        string Payment_Mode = row["Payment_Mode"].ToString();
                        string RepeatInfo = "0";
                        string Cheque_No = "0";
                        string DateBillCreated = today;

                        cmd2.Parameters.AddWithValue("@InvoiceNo", invoiceno);
                        cmd2.Parameters.AddWithValue("@Company_Name", cmpnynm);
                        cmd2.Parameters.AddWithValue("@CustomerId", customerid);
                        cmd2.Parameters.AddWithValue("@Credit", Credit);
                        cmd2.Parameters.AddWithValue("@Debit", Debit);
                        cmd2.Parameters.AddWithValue("@Balance", Balance);
                        cmd2.Parameters.AddWithValue("@RepeatInfo", RepeatInfo);
                        cmd2.Parameters.AddWithValue("@Payment_Mode", Payment_Mode);
                        cmd2.Parameters.AddWithValue("@Cheque_No", Cheque_No);
                        cmd2.Parameters.AddWithValue("@DateBillCreated", DateBillCreated);


                        cmd2.ExecuteNonQuery();

                        Response.Write("<br>data Inserted;invoice is:" + invoiceno);
                    }
                }


            }
            connection.Close();
        }*//*private void getDetailofsixmonth()
    {
            string query = "select * from Ledger_Main_log where RepeatInfo ='6'";
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["mycs"].ConnectionString;
            SqlConnection connection = new SqlConnection(ConnectionString);
            SqlDataAdapter adapter = new SqlDataAdapter(query, connection);
            adapter = new SqlDataAdapter(query, connection);
            DataTable dtCustomerdetails = new DataTable();

            connection.Open();
            adapter.Fill(dtCustomerdetails);


            var CustomerId = (from r in dtCustomerdetails.AsEnumerable()
                              select r["CustomerId"]).Distinct().ToList();


            DataView dv = new DataView(dtCustomerdetails);
            foreach (var item in CustomerId)
            {

                dv.RowFilter = "CustomerId = " + item + "";
                DataTable dtofitems = new DataTable();
                dtofitems = dv.ToTable();


                foreach (DataRow row in dtofitems.Rows)
                {
                    string dateInString = row["DateBillCreated"].ToString();
                    DateTime startDate = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);

                    string today = DateTime.Now.ToString("dd-MM-yyyy");

                    string formattedStartDate = startDate.ToString("dd-MM-yyyy HH:mm", CultureInfo.InvariantCulture);
                    DateTime d = DateTime.ParseExact(dateInString, "dd-MM-yyyy", CultureInfo.InvariantCulture);
                    DateTime expiryDate = d.AddDays(180);

                    string formattedexpiryDate = expiryDate.ToString("dd-MM-yyyy");
                    if (today == formattedexpiryDate)
                    {
                        Response.Write("bill generate");
                    }
                    else
                    {
                        string insertQuery = "insert into " +
                     "Ledger_Main_log (InvoiceNo,Company_Name,CustomerId,Credit,Debit,Balance,Payment_Mode,RepeatInfo,Cheque_No,DateBillCreated) " +
                     "values(@InvoiceNo,@Company_Name,@CustomerId,@Credit,@Debit,@Balance,@Payment_Mode,@RepeatInfo,@Cheque_No,@DateBillCreated)";


                        SqlCommand cmd2 = new SqlCommand(insertQuery, connection);

                        string cmpnynm = row["Company_Name"].ToString();
                        string res = cmpnynm.Substring(0, 3).ToUpper();
                        string invoiceno = res + DateTime.Now.ToString("yyyy") + GenerateRandomNo();


                        string customerid = row["CustomerId"].ToString();
                        string Credit = row["Credit"].ToString();
                        string Debit = row["Debit"].ToString();
                        string Balance = (int.Parse(row["Balance"].ToString()) + GetDuebyid(customerid)).ToString();
                        string Payment_Mode = row["Payment_Mode"].ToString();
                        string RepeatInfo = "0";
                        string Cheque_No = "0";
                        string DateBillCreated = today;

                        cmd2.Parameters.AddWithValue("@InvoiceNo", invoiceno);
                        cmd2.Parameters.AddWithValue("@Company_Name", cmpnynm);
                        cmd2.Parameters.AddWithValue("@CustomerId", customerid);
                        cmd2.Parameters.AddWithValue("@Credit", Credit);
                        cmd2.Parameters.AddWithValue("@Debit", Debit);
                        cmd2.Parameters.AddWithValue("@Balance", Balance);
                        cmd2.Parameters.AddWithValue("@RepeatInfo", RepeatInfo);
                        cmd2.Parameters.AddWithValue("@Payment_Mode", Payment_Mode);
                        cmd2.Parameters.AddWithValue("@Cheque_No", Cheque_No);
                        cmd2.Parameters.AddWithValue("@DateBillCreated", DateBillCreated);


                        cmd2.ExecuteNonQuery();

                        Response.Write("<br>data Inserted;invoice is:" + invoiceno);
                    }
                }


            }
            connection.Close();
        }*/
    private int GetDuebyid(string idcustomer)
    {

        string val = "";
        int xyz = 0;
        try
        {
            string query = "select Balance from Ledger_Main_log where CustomerId = '" + idcustomer + "'";
            string ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["mycs"].ConnectionString;
            SqlConnection connection = new SqlConnection(ConnectionString);
            SqlDataAdapter adapter = new SqlDataAdapter(query, connection);
            adapter = new SqlDataAdapter(query, connection);
            DataTable dtDue = new DataTable();

            connection.Open();
            adapter.Fill(dtDue);
            connection.Close();



            val = dtDue.Rows[dtDue.Rows.Count - 1]["Balance"].ToString();




            xyz = int.Parse(val.ToString());


        }
        catch (Exception) { }

        return xyz;
    }
    public int GenerateRandomNo()
    {
        int _min = 1000;
        int _max = 9999;
        Random _rdm = new Random();
        return _rdm.Next(_min, _max);
    }
}

}
/*string query1 = "select distinct * from Ledger_Main_log where InvoiceNo='" + item1 + "'";

                    SqlDataAdapter adapter1 = new SqlDataAdapter(query, connection);
                    adapter = new SqlDataAdapter(query1, connection);
                    DataTable dtCustomerdetailsforitem = new DataTable();

                    connection.Open();
                    adapter.Fill(dtCustomerdetailsforitem);
                    connection.Close();
*/


/*string ConnectionString2 = System.Configuration.ConfigurationManager.ConnectionStrings["mycs"].ConnectionString;
                    SqlConnection connection2 = new SqlConnection(ConnectionString2);
                    string insertQuery = "insert into " +
                         "Ledger_Main_log (InvoiceNo,Company_Name,CustomerId,Credit,Debit,Balance,Payment_Mode,RepeatInfo,Cheque_No,DateBillCreated) " +
                         "values(@InvoiceNo,@Company_Name,@CustomerId,@Credit,@Debit,@Balance,@Payment_Mode,@RepeatInfo,@Cheque_No,@DateBillCreated)";


                    SqlCommand cmd2 = new SqlCommand(insertQuery, connection2);
                    connection2.Open();
                    foreach (var item1 in Invoiceno)
                    {
                        string query1 = "select distinct * from Ledger_Main_log where InvoiceNo='" + item1 + "'";

                        SqlDataAdapter adapter1 = new SqlDataAdapter(query, connection);
                        adapter = new SqlDataAdapter(query1, connection);
                        DataTable dtCustomerdetailsforitem = new DataTable();


                        adapter.Fill(dtCustomerdetailsforitem);


                        string cmpnynm = dtCustomerdetailsforitem.Rows[0]["Company_Name"].ToString();
                        string res = cmpnynm.Substring(0, 3).ToUpper();
                        string invoiceno = res + DateTime.Now.ToString("yyyy") + GenerateRandomNo();


                        string customerid = dtCustomerdetailsforitem.Rows[0]["CustomerId"].ToString();
                        string Credit = dtCustomerdetailsforitem.Rows[0]["Credit"].ToString();
                        string Debit = dtCustomerdetailsforitem.Rows[0]["Debit"].ToString();
                        string Balance = (int.Parse(dtCustomerdetailsforitem.Rows[0]["Balance"].ToString()) + GetDuebyid(customerid)).ToString();
                        string Payment_Mode = dtCustomerdetailsforitem.Rows[0]["Payment_Mode"].ToString();
                        string RepeatInfo = "0";
                        string Cheque_No = "0";
                        string DateBillCreated = today;







                        cmd2.Parameters.AddWithValue("@InvoiceNo", invoiceno);
                        cmd2.Parameters.AddWithValue("@Company_Name", cmpnynm);
                        cmd2.Parameters.AddWithValue("@CustomerId", CustomerId);
                        cmd2.Parameters.AddWithValue("@Credit", Credit);
                        cmd2.Parameters.AddWithValue("@Debit", Debit);
                        cmd2.Parameters.AddWithValue("@Balance", Balance);
                        cmd2.Parameters.AddWithValue("@RepeatInfo", RepeatInfo);
                        cmd2.Parameters.AddWithValue("@Payment_Mode", Payment_Mode);
                        cmd2.Parameters.AddWithValue("@Cheque_No", Cheque_No);
                        cmd2.Parameters.AddWithValue("@DateBillCreated", DateBillCreated);


                        cmd2.ExecuteNonQuery();


                    }
                    connection2.Close();

*/